# Generated by Django 4.2.5 on 2023-09-18 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagCorrelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlation_coefficient', models.FloatField()),
                ('tag1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag1_correlations', to='recommend.tag')),
                ('tag2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag2_correlations', to='recommend.tag')),
            ],
            options={
                'db_table': 'tag_correlation',
            },
        ),
    ]
